services:
  db:
    image: postgres:16-alpine
    container_name: 69-s3-db
    ports:
      - "54327:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

  admin:
    image: dpage/pgadmin4
    container_name: 69-s3-pgadmin
    ports:
      - "8084:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    depends_on:
      - db
    restart: unless-stopped

  my_app:
    image: prawee/strapi
    container_name: my_app
    ports:
      - "${APP_PORT}:1337"
    environment:
      - DATABASE_CLIENT=${DATABASE_CLIENT}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DB_NAME}
      - DATABASE_USERNAME=${DB_USER}
      - DATABASE_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db
    restart: unless-stopped

volumes:
  db_data: