services:
  db:
    image: postgres:16-alpine
    container_name: 69-s3-db
    ports:
      - "54327:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=narasuep.s
      - POSTGRES_DB=narasuep.s
    # ตรงนี้แหละครับที่อาจารย์ต้องการ (Map Volume กันข้อมูลหาย)
    volumes:
      - db_data:/var/lib/postgresql/data

  admin:
    image: dpage/pgadmin4
    container_name: 69-s3-pgadmin
    ports:
      - "8084:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=narasuep-s@rmutp.ac.th
      - PGADMIN_DEFAULT_PASSWORD=password
    depends_on:
      - db

# ประกาศ Volume ที่ด้านล่างสุด
volumes:
  db_data:
